// VYNTEX HAUL: industry pack for junk removal & moving.
// Everything industry-specific lives here. The app core never checks the industry id.
import type { IndustryPack } from '../types';
import { fieldPack } from '../blueprint';

export const haulPack: IndustryPack = /* @__PURE__ */ fieldPack({
  id: "haul",
  product: "VYNTEX HAUL",
  label: { en: "Junk removal & moving", es: "Retiro de basura y mudanzas" },
  blurb: { en: "For junk removal, cleanout and small moving crews.", es: "Para cuadrillas de retiro de basura, vaciado de casas y mudanzas pequeñas." },
  ticketPrefix: "VH-",
  recurring: false,
  sampleCompany: { name: "Sample Haul & Move LLC", initials: "HM", license: "Fully insured", phone: "609-555-0500", email: "book@example.com" },
  serviceTypes: [
    { id: "junk", en: "Junk removal", es: "Retiro de basura" },
    { id: "cleanout", en: "Estate / house cleanout", es: "Vaciado de casa" },
    { id: "local", en: "Local move", es: "Mudanza local" },
    { id: "longdist", en: "Long-distance move", es: "Mudanza de larga distancia" },
    { id: "packing", en: "Packing", es: "Empaque" },
    { id: "heavy", en: "Piano & heavy items", es: "Piano y objetos pesados" },
    { id: "debris", en: "Construction debris", es: "Escombros de construcción" },
    { id: "other", en: "Other", es: "Otro" },
  ],
  terms: {
    en: {
      "workersPlural": "Crew members",
      "owner": "Owner",
      "projects": "Jobs",
      "project": "Job",
      "newProject": "New job",
      "back": "All jobs",
      "deleteProject": "Delete job",
      "name": "Job name",
      "noProjects": "No jobs match. Clear the filters or add a new job.",
      "subs": "Crew",
      "sub": "Crew member",
      "secAssign": "Who is on the crew",
      "secSubPay": "Payments to crew",
      "addSubPay": "Pay a crew member",
      "paySub": "Pay a crew member",
      "paidSubs": "Paid to crew",
      "oweSubs": "You owe crew",
      "subLabor": "Crew labor",
      "newSub": "New crew member",
      "subName": "Full name or business name",
      "allSubs": "All crew",
      "addAssign": "Assign crew",
      "trade": "Role",
      "pt_project": "Per job (fixed price)",
      "contract": "Price",
      "contractBtn": "Agreement",
      "activeProjects": "Active jobs",
      "contractValue": "Active job value",
      "activeList": "Active jobs",
      "secTasks": "Checklist & tasks",
      "newTask": "New checklist item",
      "task": "Checklist item",
      "secLog": "Notes from the crew",
      "scope": "Work details (for the agreement)",
      "payTerms": "Price and billing (for the agreement)",
      "end": "End date (optional)",
      "repeat": "Repeats",
      "rp_once": "One time",
      "rp_weekly": "Every week",
      "rp_biweekly": "Every 2 weeks",
      "rp_monthly": "Every month",
      "jobSite": "Service address",
      "contractTotal": "Job total",
      "st_progress": "Active",
      "industry": "Industry",
      "thanks": "Thank you for choosing {company}!",
      "materials": "Fuel, dump & truck fees",
      "secPurch": "Fuel, dump & truck fees",
      "addPurch": "Add fee",
      "desc": "What it was for",
      "ev_start": "Job day",
      "ev_end": "Job ends",
      "start": "Job date"
    },
    es: {
      "workersPlural": "Miembros de cuadrilla",
      "owner": "Dueño",
      "projects": "Trabajos",
      "project": "Trabajo",
      "newProject": "Nuevo trabajo",
      "back": "Todos los trabajos",
      "deleteProject": "Borrar trabajo",
      "name": "Nombre del trabajo",
      "noProjects": "Ningún trabajo coincide. Quite los filtros o agregue uno.",
      "subs": "Cuadrilla",
      "sub": "Miembro de cuadrilla",
      "secAssign": "Quién está en la cuadrilla",
      "secSubPay": "Pagos a la cuadrilla",
      "addSubPay": "Pagar a un miembro",
      "paySub": "Pagar a un miembro",
      "paidSubs": "Pagado a la cuadrilla",
      "oweSubs": "Usted debe a la cuadrilla",
      "subLabor": "Mano de obra",
      "newSub": "Nuevo miembro",
      "subName": "Nombre completo o de la empresa",
      "allSubs": "Toda la cuadrilla",
      "addAssign": "Asignar cuadrilla",
      "trade": "Función",
      "pt_project": "Por trabajo (precio fijo)",
      "contract": "Precio",
      "contractBtn": "Acuerdo",
      "activeProjects": "Trabajos activos",
      "contractValue": "Valor de trabajos activos",
      "activeList": "Trabajos activos",
      "secTasks": "Lista de tareas",
      "newTask": "Nuevo punto de la lista",
      "task": "Punto de la lista",
      "secLog": "Notas de la cuadrilla",
      "scope": "Detalles del trabajo (para el acuerdo)",
      "payTerms": "Precio y cobro (para el acuerdo)",
      "end": "Fecha final (opcional)",
      "repeat": "Se repite",
      "rp_once": "Una vez",
      "rp_weekly": "Cada semana",
      "rp_biweekly": "Cada 2 semanas",
      "rp_monthly": "Cada mes",
      "jobSite": "Dirección del servicio",
      "contractTotal": "Total del trabajo",
      "st_progress": "Activo",
      "industry": "Industria",
      "thanks": "¡Gracias por elegir a {company}!",
      "materials": "Gasolina, vertedero y camión",
      "secPurch": "Gasolina, vertedero y camión",
      "addPurch": "Agregar gasto",
      "desc": "Para qué fue",
      "ev_start": "Día del trabajo",
      "ev_end": "Termina el trabajo",
      "start": "Fecha del trabajo"
    },
  },
  jobStatuses: ['estimate', 'contract', 'progress', 'hold', 'done'],
  kpis: ["activeJobs","visitsThisWeek","collectedMonth","clientsOwe","oweWorkers","newLeads"],
  agreement: {
    en: {
      "title": "Moving and Hauling Service Agreement",
      "intro": "This agreement is between {company} (\"Company\") and the client named below (\"Client\").",
      "s1": "1. Services",
      "s2": "2. Price and payment",
      "total": "Price",
      "s3": "3. Schedule",
      "sched": "Job date: {start}. Arrival window is confirmed the day before.",
      "s4": "4. Items, fees and liability",
      "chg": "Price is based on the items and volume described. Extra items, stairs, long carries or additional dump loads are charged as agreed on site. Hazardous materials (paint, chemicals, tires) are not accepted unless agreed in writing. Report any damage within 48 hours.",
      "s5": "5. Insurance",
      "ins": "Company carries general liability insurance. Insurer: ____________________ Phone: ____________________",
      "s6": "6. Cancellations",
      "cxl": "Cancel at least 48 hours before the job to receive the deposit back.",
      "s7": "7. Electronic signatures",
      "esig": "The parties agree that this agreement may be signed electronically. An electronic signature has the same legal effect as a handwritten signature under the federal ESIGN Act (15 U.S.C. § 7001 et seq.) and the New Jersey Uniform Electronic Transactions Act (N.J.S.A. 12A:12-1 et seq.).",
      "draft": "Draft template. Have an attorney review the final wording before using it with clients."
    },
    es: {
      "title": "Acuerdo de Servicio de Mudanza y Retiro",
      "intro": "Este acuerdo es entre {company} (\"la Compañía\") y el cliente nombrado abajo (\"el Cliente\").",
      "s1": "1. Servicios",
      "s2": "2. Precio y pago",
      "total": "Precio",
      "s3": "3. Calendario",
      "sched": "Fecha del trabajo: {start}. La ventana de llegada se confirma el día anterior.",
      "s4": "4. Artículos, cargos y responsabilidad",
      "chg": "El precio se basa en los artículos y volumen descritos. Artículos extra, escaleras, distancias largas o cargas adicionales al vertedero se cobran según lo acordado. No se aceptan materiales peligrosos (pintura, químicos, llantas) salvo acuerdo por escrito. Reporte cualquier daño dentro de 48 horas.",
      "s5": "5. Seguro",
      "ins": "La Compañía tiene seguro de responsabilidad civil. Aseguradora: ____________________ Teléfono: ____________________",
      "s6": "6. Cancelaciones",
      "cxl": "Cancele con al menos 48 horas de anticipación para recuperar el depósito.",
      "s7": "7. Firmas electrónicas",
      "esig": "Las partes acuerdan que este acuerdo puede firmarse electrónicamente. Una firma electrónica tiene el mismo efecto legal que una firma a mano bajo la ley federal ESIGN (15 U.S.C. § 7001 y siguientes) y la Ley Uniforme de Transacciones Electrónicas de Nueva Jersey (N.J.S.A. 12A:12-1 y siguientes).",
      "draft": "Plantilla en borrador. Un abogado debe revisar el texto final antes de usarlo con clientes."
    },
  },
  kickoffTasks: [
    { en: "Send the agreement and collect the deposit", es: "Enviar el acuerdo y cobrar el depósito", dueIn: 0, for: 'owner', pri: 'high' },
    { en: "Confirm the arrival window, parking and stairs or elevator", es: "Confirmar la ventana de llegada, el estacionamiento y si hay escaleras o elevador", dueIn: 1, for: 'owner' },
    { en: "Ask about heavy, fragile or hazardous items", es: "Preguntar por objetos pesados, frágiles o peligrosos", dueIn: 1, for: 'owner' },
    { en: "Assign the truck and the crew", es: "Asignar el camión y la cuadrilla", dueIn: 2, for: 'owner' },
    { en: "Call the client the day before to confirm", es: "Llamar al cliente un día antes para confirmar", dueIn: 3, for: 'owner', pri: 'low' },
  ],
  closeoutTasks: [
    { en: "Send the final invoice or receipt", es: "Enviar la factura final o el recibo", dueIn: 0, for: 'owner', pri: 'high' },
    { en: "Record the dump tickets and fuel for this job", es: "Registrar los tickets del vertedero y la gasolina de este trabajo", dueIn: 0, for: 'owner' },
    { en: "Pay the crew", es: "Pagar a la cuadrilla", dueIn: 1, for: 'owner' },
    { en: "Ask the client for a review", es: "Pedir una reseña al cliente", dueIn: 3, for: 'owner', pri: 'low' },
  ],
  compliance: true,
});
