// VYNTEX CLEAN: industry pack for cleaning.
// Everything industry-specific lives here. The app core never checks the industry id.
import type { IndustryPack } from '../types';
import { fieldPack } from '../blueprint';

export const cleanPack: IndustryPack = /* @__PURE__ */ fieldPack({
  id: "clean",
  product: "VYNTEX CLEAN",
  label: { en: "Cleaning", es: "Limpieza" },
  blurb: { en: "For house cleaning, office cleaning and rental turnovers.", es: "Para limpieza de casas, oficinas y rentas vacacionales." },
  ticketPrefix: "VC-",
  recurring: true,
  sampleCompany: { name: "Sparkle Sample Cleaning LLC", initials: "SC", license: "Fully insured", phone: "609-555-0200", email: "samplecleaning@example.com" },
  serviceTypes: [
    { id: "standard", en: "Standard cleaning", es: "Limpieza regular" },
    { id: "deep", en: "Deep cleaning", es: "Limpieza profunda" },
    { id: "moveout", en: "Move-in / move-out", es: "Mudanza (entrada / salida)" },
    { id: "postcon", en: "Post-construction", es: "Post-construcción" },
    { id: "office", en: "Office / commercial", es: "Oficina / comercial" },
    { id: "rental", en: "Short-term rental turnover", es: "Rentas cortas (Airbnb)" },
    { id: "windows", en: "Windows", es: "Ventanas" },
    { id: "carpet", en: "Carpet & upholstery", es: "Alfombras y tapicería" },
    { id: "other", en: "Other", es: "Otro" },
  ],
  terms: {
    en: {
      "owner": "Owner",
      "projects": "Jobs",
      "project": "Job",
      "newProject": "New job",
      "back": "All jobs",
      "deleteProject": "Delete job",
      "name": "Job name",
      "noProjects": "No jobs match. Clear the filters or add a new job.",
      "subs": "Cleaners",
      "sub": "Cleaner",
      "secAssign": "Who is cleaning",
      "secSubPay": "Payments to cleaners",
      "addSubPay": "Pay a cleaner",
      "paySub": "Pay a cleaner",
      "paidSubs": "Paid to cleaners",
      "oweSubs": "You owe cleaners",
      "subLabor": "Cleaner labor",
      "newSub": "New cleaner",
      "subName": "Full name",
      "allSubs": "All cleaners",
      "addAssign": "Assign a cleaner",
      "part": "Rooms / area",
      "trade": "Role",
      "materials": "Supplies & purchases",
      "secPurch": "Supplies & purchases",
      "addPurch": "Add supplies",
      "desc": "What was bought",
      "scope": "Cleaning details (for the agreement)",
      "payTerms": "Price and billing (for the agreement)",
      "contract": "Price",
      "contractBtn": "Agreement",
      "activeProjects": "Active jobs",
      "contractValue": "Active job value",
      "activeList": "Active jobs",
      "secTasks": "Checklist & tasks",
      "newTask": "New checklist item",
      "task": "Checklist item",
      "secLog": "Notes from cleaners",
      "ev_start": "Cleaning",
      "ev_end": "Last cleaning",
      "start": "First cleaning",
      "end": "End date (optional)",
      "repeat": "Repeats",
      "rp_once": "One time",
      "rp_weekly": "Every week",
      "rp_biweekly": "Every 2 weeks",
      "rp_monthly": "Every month",
      "jobSite": "Service address",
      "contractTotal": "Service total",
      "st_contract": "Waiting on agreement",
      "st_progress": "Active",
      "thanks": "Thank you for choosing us!",
      "industry": "Industry",
      "pt_project": "Per job (fixed price)",
      "forProject": "Job",
      "convert": "Make it a job",
      "converted": "Job created",
      "search": "Search client, address or job",
      "confirmReset": "Throw away your edits and rebuild this document from the job details?"
    },
    es: {
      "owner": "Dueño",
      "projects": "Trabajos",
      "project": "Trabajo",
      "newProject": "Nuevo trabajo",
      "back": "Todos los trabajos",
      "deleteProject": "Borrar trabajo",
      "name": "Nombre del trabajo",
      "noProjects": "Ningún trabajo coincide. Quite los filtros o agregue uno.",
      "subs": "Limpiadores",
      "sub": "Limpiador(a)",
      "secAssign": "Quién limpia",
      "secSubPay": "Pagos a limpiadores",
      "addSubPay": "Pagar a limpiador(a)",
      "paySub": "Pagar a limpiador(a)",
      "paidSubs": "Pagado a limpiadores",
      "oweSubs": "Usted debe a limpiadores",
      "subLabor": "Mano de obra de limpieza",
      "newSub": "Nuevo(a) limpiador(a)",
      "subName": "Nombre completo",
      "allSubs": "Todos los limpiadores",
      "addAssign": "Asignar limpiador(a)",
      "part": "Cuartos / área",
      "trade": "Función",
      "materials": "Productos y compras",
      "secPurch": "Productos y compras",
      "addPurch": "Agregar productos",
      "desc": "Qué se compró",
      "scope": "Detalles de la limpieza (para el acuerdo)",
      "payTerms": "Precio y cobro (para el acuerdo)",
      "contract": "Precio",
      "contractBtn": "Acuerdo",
      "activeProjects": "Trabajos activos",
      "contractValue": "Valor de trabajos activos",
      "activeList": "Trabajos activos",
      "secTasks": "Lista de tareas",
      "newTask": "Nuevo punto de la lista",
      "task": "Punto de la lista",
      "secLog": "Notas de los limpiadores",
      "ev_start": "Limpieza",
      "ev_end": "Última limpieza",
      "start": "Primera limpieza",
      "end": "Fecha final (opcional)",
      "repeat": "Se repite",
      "rp_once": "Una vez",
      "rp_weekly": "Cada semana",
      "rp_biweekly": "Cada 2 semanas",
      "rp_monthly": "Cada mes",
      "jobSite": "Dirección del servicio",
      "contractTotal": "Total del servicio",
      "st_contract": "Esperando acuerdo",
      "st_progress": "Activo",
      "thanks": "¡Gracias por elegirnos!",
      "industry": "Industria",
      "pt_project": "Por trabajo (precio fijo)",
      "forProject": "Trabajo",
      "convert": "Convertir en trabajo",
      "converted": "Trabajo creado",
      "search": "Buscar cliente, dirección o trabajo",
      "confirmReset": "¿Descartar sus cambios y volver a crear este documento con los datos del trabajo?"
    },
  },
  jobStatuses: ['estimate', 'contract', 'progress', 'hold', 'done'],
  kpis: ["activeJobs","recurringClients","visitsThisWeek","clientsOwe","oweWorkers","newLeads"],
  agreement: {
    en: {
      "title": "Cleaning Service Agreement",
      "intro": "This agreement is between {company} (\"Company\") and the client named below (\"Client\").",
      "s1": "1. Cleaning services",
      "s2": "2. Price and payment",
      "total": "Price",
      "s3": "3. Schedule",
      "sched": "First cleaning: {start}. Recurring visits follow the schedule agreed below. The Client may pause or change the schedule with 48 hours' notice.",
      "s4": "4. Extra services, damage and satisfaction",
      "chg": "Extra services (inside oven, fridge, windows, laundry) are quoted and added in writing. Any breakage must be reported within 24 hours. If something was missed, tell us within 24 hours and we will return to re-clean that area at no charge.",
      "s5": "5. Insurance",
      "ins": "Company carries general liability insurance. Insurer: ____________________ Phone: ____________________",
      "s6": "6. Cancellations and access",
      "cxl": "Please cancel or reschedule at least 24 hours before a visit. If our team cannot get in at the scheduled time, a lockout fee of $______ may apply. Keys and access codes are kept secure and returned when service ends.",
      "s7": "7. Electronic signatures",
      "esig": "The parties agree that this agreement may be signed electronically. An electronic signature has the same legal effect as a handwritten signature under the federal ESIGN Act (15 U.S.C. § 7001 et seq.) and the New Jersey Uniform Electronic Transactions Act (N.J.S.A. 12A:12-1 et seq.).",
      "draft": "Draft template. Have an attorney review the final wording before using it with clients."
    },
    es: {
      "title": "Acuerdo de Servicio de Limpieza",
      "intro": "Este acuerdo es entre {company} (\"la Compañía\") y el cliente nombrado abajo (\"el Cliente\").",
      "s1": "1. Servicios de limpieza",
      "s2": "2. Precio y pago",
      "total": "Precio",
      "s3": "3. Calendario",
      "sched": "Primera limpieza: {start}. Las visitas siguientes siguen el calendario acordado. El Cliente puede pausar o cambiar el calendario con 48 horas de aviso.",
      "s4": "4. Servicios extra, daños y satisfacción",
      "chg": "Los servicios extra (dentro del horno, refrigerador, ventanas, lavandería) se cotizan y se agregan por escrito. Cualquier daño debe reportarse dentro de 24 horas. Si algo quedó pendiente, avísenos dentro de 24 horas y regresamos a limpiar esa área sin costo.",
      "s5": "5. Seguro",
      "ins": "La Compañía tiene seguro de responsabilidad civil. Aseguradora: ____________________ Teléfono: ____________________",
      "s6": "6. Cancelaciones y acceso",
      "cxl": "Cancele o cambie la cita con al menos 24 horas de anticipación. Si nuestro equipo no puede entrar a la hora programada, puede aplicar un cargo de $______. Las llaves y códigos se guardan de forma segura y se devuelven al terminar el servicio.",
      "s7": "7. Firmas electrónicas",
      "esig": "Las partes acuerdan que este acuerdo puede firmarse electrónicamente. Una firma electrónica tiene el mismo efecto legal que una firma a mano bajo la ley federal ESIGN (15 U.S.C. § 7001 y siguientes) y la Ley Uniforme de Transacciones Electrónicas de Nueva Jersey (N.J.S.A. 12A:12-1 y siguientes).",
      "draft": "Plantilla en borrador. Un abogado debe revisar el texto final antes de usarlo con clientes."
    },
  },
  kickoffTasks: [
    { en: "Send the service agreement", es: "Enviar el acuerdo de servicio", dueIn: 0, for: 'owner', pri: 'high' },
    { en: "Confirm how the cleaner gets in (key, lockbox, alarm)", es: "Confirmar cómo entra la limpiadora (llave, caja de llaves, alarma)", dueIn: 1, for: 'owner', pri: 'high' },
    { en: "Write down pets, allergies and rooms to skip", es: "Anotar mascotas, alergias y cuartos que no se limpian", dueIn: 1, for: 'owner' },
    { en: "Assign the cleaner and share the checklist", es: "Asignar a la limpiadora y compartir la lista de tareas", dueIn: 2, for: 'owner' },
    { en: "Call the client after the first cleaning", es: "Llamar al cliente después de la primera limpieza", dueIn: 7, for: 'owner', pri: 'low' },
  ],
  closeoutTasks: [
    { en: "Send the invoice or charge the card on file", es: "Enviar la factura o cobrar a la tarjeta registrada", dueIn: 0, for: 'owner', pri: 'high' },
    { en: "Return keys and remove door codes from our notes", es: "Devolver las llaves y borrar los códigos de acceso de nuestras notas", dueIn: 1, for: 'owner' },
    { en: "Ask the client for a review", es: "Pedir una reseña al cliente", dueIn: 2, for: 'owner', pri: 'low' },
    { en: "Offer regular service", es: "Ofrecer servicio regular", dueIn: 5, for: 'owner', pri: 'low' },
  ],
  compliance: true,
});
