// VYNTEX WASH: industry pack for pressure washing, windows & gutters.
// Everything industry-specific lives here. The app core never checks the industry id.
import type { IndustryPack } from '../types';
import { seed } from './seed';

export const washPack: IndustryPack = {
  id: "wash",
  product: "VYNTEX WASH",
  label: { en: "Pressure washing, windows & gutters", es: "Lavado a presión, ventanas y canaletas" },
  blurb: { en: "For pressure washing, window and gutter cleaning.", es: "Para lavado a presión, ventanas y canaletas." },
  ticketPrefix: "VW-",
  recurring: true,
  sampleCompany: { name: "BrightSide Sample Exterior Cleaning LLC", initials: "BS", license: "Fully insured", phone: "609-555-0400", email: "samplewash@example.com" },
  serviceTypes: [
    { id: "house", en: "House wash", es: "Lavado de casa" },
    { id: "roof", en: "Roof soft wash", es: "Lavado suave de techo" },
    { id: "concrete", en: "Driveway & concrete", es: "Entrada y concreto" },
    { id: "deck", en: "Deck & fence", es: "Deck y cerca" },
    { id: "windows", en: "Window cleaning", es: "Limpieza de ventanas" },
    { id: "gutters", en: "Gutter cleaning", es: "Limpieza de canaletas" },
    { id: "storefront", en: "Commercial storefront", es: "Fachada comercial" },
    { id: "other", en: "Other", es: "Otro" },
  ],
  terms: {
    en: {
      "workersPlural": "Crew members",
      "owner": "Owner",
      "projects": "Jobs",
      "project": "Job",
      "newProject": "New job",
      "back": "All jobs",
      "deleteProject": "Delete job",
      "name": "Job name",
      "noProjects": "No jobs match. Clear the filters or add a new job.",
      "subs": "Crew",
      "sub": "Crew member",
      "secAssign": "Who is on the crew",
      "secSubPay": "Payments to crew",
      "addSubPay": "Pay a crew member",
      "paySub": "Pay a crew member",
      "paidSubs": "Paid to crew",
      "oweSubs": "You owe crew",
      "subLabor": "Crew labor",
      "newSub": "New crew member",
      "subName": "Full name or business name",
      "allSubs": "All crew",
      "addAssign": "Assign crew",
      "trade": "Role",
      "contract": "Price",
      "contractBtn": "Agreement",
      "activeProjects": "Active jobs",
      "contractValue": "Active job value",
      "activeList": "Active jobs",
      "secTasks": "Checklist & tasks",
      "newTask": "New checklist item",
      "task": "Checklist item",
      "secLog": "Notes from the crew",
      "scope": "Work details (for the agreement)",
      "payTerms": "Price and billing (for the agreement)",
      "end": "End date (optional)",
      "repeat": "Repeats",
      "rp_once": "One time",
      "rp_weekly": "Every week",
      "rp_biweekly": "Every 2 weeks",
      "rp_monthly": "Every month",
      "jobSite": "Service address",
      "contractTotal": "Job total",
      "st_progress": "Active",
      "industry": "Industry",
      "thanks": "Thank you for choosing {company}!",
      "materials": "Chemicals & supplies",
      "secPurch": "Chemicals & supplies",
      "addPurch": "Add supplies",
      "ev_start": "Service",
      "ev_end": "Job ends",
      "start": "Service date / first visit",
      "pt_project": "Per job (fixed price)",
      "forProject": "Job",
      "convert": "Make it a job",
      "converted": "Job created",
      "search": "Search client, address or job",
      "confirmReset": "Throw away your edits and rebuild this document from the job details?"
    },
    es: {
      "workersPlural": "Miembros de cuadrilla",
      "owner": "Dueño",
      "projects": "Trabajos",
      "project": "Trabajo",
      "newProject": "Nuevo trabajo",
      "back": "Todos los trabajos",
      "deleteProject": "Borrar trabajo",
      "name": "Nombre del trabajo",
      "noProjects": "Ningún trabajo coincide. Quite los filtros o agregue uno.",
      "subs": "Cuadrilla",
      "sub": "Miembro de cuadrilla",
      "secAssign": "Quién está en la cuadrilla",
      "secSubPay": "Pagos a la cuadrilla",
      "addSubPay": "Pagar a un miembro",
      "paySub": "Pagar a un miembro",
      "paidSubs": "Pagado a la cuadrilla",
      "oweSubs": "Usted debe a la cuadrilla",
      "subLabor": "Mano de obra",
      "newSub": "Nuevo miembro",
      "subName": "Nombre completo o de la empresa",
      "allSubs": "Toda la cuadrilla",
      "addAssign": "Asignar cuadrilla",
      "trade": "Función",
      "contract": "Precio",
      "contractBtn": "Acuerdo",
      "activeProjects": "Trabajos activos",
      "contractValue": "Valor de trabajos activos",
      "activeList": "Trabajos activos",
      "secTasks": "Lista de tareas",
      "newTask": "Nuevo punto de la lista",
      "task": "Punto de la lista",
      "secLog": "Notas de la cuadrilla",
      "scope": "Detalles del trabajo (para el acuerdo)",
      "payTerms": "Precio y cobro (para el acuerdo)",
      "end": "Fecha final (opcional)",
      "repeat": "Se repite",
      "rp_once": "Una vez",
      "rp_weekly": "Cada semana",
      "rp_biweekly": "Cada 2 semanas",
      "rp_monthly": "Cada mes",
      "jobSite": "Dirección del servicio",
      "contractTotal": "Total del trabajo",
      "st_progress": "Activo",
      "industry": "Industria",
      "thanks": "¡Gracias por elegir a {company}!",
      "materials": "Químicos y productos",
      "secPurch": "Químicos y productos",
      "addPurch": "Agregar productos",
      "ev_start": "Servicio",
      "ev_end": "Termina el trabajo",
      "start": "Fecha de servicio / primera visita",
      "pt_project": "Por trabajo (precio fijo)",
      "forProject": "Trabajo",
      "convert": "Convertir en trabajo",
      "converted": "Trabajo creado",
      "search": "Buscar cliente, dirección o trabajo",
      "confirmReset": "¿Descartar sus cambios y volver a crear este documento con los datos del trabajo?"
    },
  },
  jobStatuses: ['estimate', 'contract', 'progress', 'hold', 'done'],
  kpis: ["activeJobs","visitsThisWeek","collectedMonth","clientsOwe","oweWorkers","newLeads"],
  agreement: {
    en: {
      "title": "Exterior Cleaning Service Agreement",
      "intro": "This agreement is between {company} (\"Company\") and the client named below (\"Client\").",
      "s1": "1. Services",
      "s2": "2. Price and payment",
      "total": "Price",
      "s3": "3. Schedule",
      "sched": "Service date: {start}. Recurring services follow the agreed schedule. Rain may move a visit to the next available day.",
      "s4": "4. Property, water and results",
      "chg": "Client provides access to an outdoor water supply. Company pre-rinses plants and covers outlets and fixtures. Some stains (rust, oil, oxidation) may not come out completely.",
      "s5": "5. Insurance",
      "ins": "Company carries general liability insurance. Insurer: ____________________ Phone: ____________________",
      "s6": "6. Cancellations",
      "cxl": "Cancel or reschedule at least 24 hours before the service.",
      "s7": "7. Electronic signatures",
      "esig": "The parties agree that this agreement may be signed electronically. An electronic signature has the same legal effect as a handwritten signature under the federal ESIGN Act (15 U.S.C. § 7001 et seq.) and the New Jersey Uniform Electronic Transactions Act (N.J.S.A. 12A:12-1 et seq.).",
      "draft": "Draft template. Have an attorney review the final wording before using it with clients."
    },
    es: {
      "title": "Acuerdo de Servicio de Limpieza Exterior",
      "intro": "Este acuerdo es entre {company} (\"la Compañía\") y el cliente nombrado abajo (\"el Cliente\").",
      "s1": "1. Servicios",
      "s2": "2. Precio y pago",
      "total": "Precio",
      "s3": "3. Calendario",
      "sched": "Fecha de servicio: {start}. Los servicios recurrentes siguen el calendario acordado. La lluvia puede mover una visita al siguiente día disponible.",
      "s4": "4. Propiedad, agua y resultados",
      "chg": "El Cliente da acceso a una llave de agua exterior. La Compañía enjuaga las plantas y cubre enchufes y lámparas. Algunas manchas (óxido, aceite, oxidación) pueden no salir por completo.",
      "s5": "5. Seguro",
      "ins": "La Compañía tiene seguro de responsabilidad civil. Aseguradora: ____________________ Teléfono: ____________________",
      "s6": "6. Cancelaciones",
      "cxl": "Cancele o cambie la cita con al menos 24 horas de anticipación.",
      "s7": "7. Firmas electrónicas",
      "esig": "Las partes acuerdan que este acuerdo puede firmarse electrónicamente. Una firma electrónica tiene el mismo efecto legal que una firma a mano bajo la ley federal ESIGN (15 U.S.C. § 7001 y siguientes) y la Ley Uniforme de Transacciones Electrónicas de Nueva Jersey (N.J.S.A. 12A:12-1 y siguientes).",
      "draft": "Plantilla en borrador. Un abogado debe revisar el texto final antes de usarlo con clientes."
    },
  },
  kickoffTasks: [
    { en: "Send the agreement", es: "Enviar el acuerdo", dueIn: 0, for: 'owner', pri: 'high' },
    { en: "Confirm water access and a working outdoor spigot", es: "Confirmar acceso al agua y una llave exterior que funcione", dueIn: 1, for: 'owner' },
    { en: "Ask the client to close windows and move cars and patio furniture", es: "Pedir al cliente que cierre ventanas y mueva autos y muebles de patio", dueIn: 2, for: 'owner' },
    { en: "Check the surfaces first: oxidation, loose paint, open outlets", es: "Revisar antes las superficies: oxidación, pintura suelta, tomacorrientes abiertos", dueIn: 2, for: 'owner' },
    { en: "Check the forecast and confirm the day", es: "Revisar el pronóstico y confirmar el día", dueIn: 3, for: 'owner' },
  ],
  closeoutTasks: [
    { en: "Send the invoice", es: "Enviar la factura", dueIn: 0, for: 'owner', pri: 'high' },
    { en: "Send the before and after photos", es: "Enviar las fotos de antes y después", dueIn: 0, for: 'owner' },
    { en: "Ask the client for a review", es: "Pedir una reseña al cliente", dueIn: 2, for: 'owner', pri: 'low' },
    { en: "Offer a yearly or seasonal plan", es: "Ofrecer un plan anual o por temporada", dueIn: 7, for: 'owner', pri: 'low' },
  ],
  compliance: true,
  seed,
};
