// VYNTEX SNOW: industry pack for snow removal.
// Everything industry-specific lives here. The app core never checks the industry id.
import type { IndustryPack } from '../types';
import { fieldPack } from '../blueprint';

export const snowPack: IndustryPack = /* @__PURE__ */ fieldPack({
  id: "snow",
  product: "VYNTEX SNOW",
  label: { en: "Snow removal", es: "Remoción de nieve" },
  blurb: { en: "For snow and ice crews: seasonal contracts and per push work.", es: "Para cuadrillas de nieve y hielo: contratos de temporada y trabajos por limpieza." },
  ticketPrefix: "VS-",
  recurring: false,
  sampleCompany: { name: "Sample Snow Pros LLC", initials: "SP", license: "Fully insured", phone: "609-555-0600", email: "dispatch@example.com" },
  serviceTypes: [
    { id: "season", en: "Seasonal contract", es: "Contrato de temporada" },
    { id: "push", en: "Per push", es: "Por cada limpieza" },
    { id: "salt", en: "Salting only", es: "Solo sal" },
    { id: "sidewalk", en: "Sidewalk shoveling", es: "Aceras con pala" },
    { id: "lot", en: "Commercial lot", es: "Estacionamiento comercial" },
    { id: "hoa", en: "HOA / community", es: "HOA / comunidad" },
    { id: "other", en: "Other", es: "Otro" },
  ],
  terms: {
    en: {
      "workersPlural": "Crew members",
      "owner": "Owner",
      "projects": "Jobs",
      "project": "Job",
      "newProject": "New job",
      "back": "All jobs",
      "deleteProject": "Delete job",
      "name": "Job name",
      "noProjects": "No jobs match. Clear the filters or add a new job.",
      "subs": "Crew",
      "sub": "Crew member",
      "secAssign": "Who is on the crew",
      "secSubPay": "Payments to crew",
      "addSubPay": "Pay a crew member",
      "paySub": "Pay a crew member",
      "paidSubs": "Paid to crew",
      "oweSubs": "You owe crew",
      "subLabor": "Crew labor",
      "newSub": "New crew member",
      "subName": "Full name or business name",
      "allSubs": "All crew",
      "addAssign": "Assign crew",
      "trade": "Role",
      "pt_project": "Per job (fixed price)",
      "contract": "Price",
      "contractBtn": "Agreement",
      "activeProjects": "Active jobs",
      "contractValue": "Active job value",
      "activeList": "Active jobs",
      "secTasks": "Storms & tasks",
      "newTask": "New storm or task",
      "task": "Storm / task",
      "secLog": "Notes from the crew",
      "scope": "Work details (for the agreement)",
      "payTerms": "Price and billing (for the agreement)",
      "end": "Season end",
      "repeat": "Repeats",
      "rp_once": "One time",
      "rp_weekly": "Every week",
      "rp_biweekly": "Every 2 weeks",
      "rp_monthly": "Every month",
      "jobSite": "Service address",
      "contractTotal": "Job total",
      "st_progress": "Active",
      "industry": "Industry",
      "thanks": "Thank you for choosing {company}!",
      "materials": "Salt, fuel & equipment",
      "secPurch": "Salt, fuel & equipment",
      "addPurch": "Add expense",
      "ev_start": "Season starts",
      "ev_end": "Season ends",
      "start": "Season start"
    },
    es: {
      "workersPlural": "Miembros de cuadrilla",
      "owner": "Dueño",
      "projects": "Trabajos",
      "project": "Trabajo",
      "newProject": "Nuevo trabajo",
      "back": "Todos los trabajos",
      "deleteProject": "Borrar trabajo",
      "name": "Nombre del trabajo",
      "noProjects": "Ningún trabajo coincide. Quite los filtros o agregue uno.",
      "subs": "Cuadrilla",
      "sub": "Miembro de cuadrilla",
      "secAssign": "Quién está en la cuadrilla",
      "secSubPay": "Pagos a la cuadrilla",
      "addSubPay": "Pagar a un miembro",
      "paySub": "Pagar a un miembro",
      "paidSubs": "Pagado a la cuadrilla",
      "oweSubs": "Usted debe a la cuadrilla",
      "subLabor": "Mano de obra",
      "newSub": "Nuevo miembro",
      "subName": "Nombre completo o de la empresa",
      "allSubs": "Toda la cuadrilla",
      "addAssign": "Asignar cuadrilla",
      "trade": "Función",
      "pt_project": "Por trabajo (precio fijo)",
      "contract": "Precio",
      "contractBtn": "Acuerdo",
      "activeProjects": "Trabajos activos",
      "contractValue": "Valor de trabajos activos",
      "activeList": "Trabajos activos",
      "secTasks": "Tormentas y tareas",
      "newTask": "Nueva tormenta o tarea",
      "task": "Tormenta / tarea",
      "secLog": "Notas de la cuadrilla",
      "scope": "Detalles del trabajo (para el acuerdo)",
      "payTerms": "Precio y cobro (para el acuerdo)",
      "end": "Fin de temporada",
      "repeat": "Se repite",
      "rp_once": "Una vez",
      "rp_weekly": "Cada semana",
      "rp_biweekly": "Cada 2 semanas",
      "rp_monthly": "Cada mes",
      "jobSite": "Dirección del servicio",
      "contractTotal": "Total del trabajo",
      "st_progress": "Activo",
      "industry": "Industria",
      "thanks": "¡Gracias por elegir a {company}!",
      "materials": "Sal, gasolina y equipo",
      "secPurch": "Sal, gasolina y equipo",
      "addPurch": "Agregar gasto",
      "ev_start": "Inicia la temporada",
      "ev_end": "Termina la temporada",
      "start": "Inicio de temporada"
    },
  },
  jobStatuses: ['estimate', 'contract', 'progress', 'hold', 'done'],
  kpis: ["activeJobs","activeValue","collectedMonth","clientsOwe","oweWorkers","newLeads"],
  agreement: {
    en: {
      "title": "Snow Removal Service Agreement",
      "intro": "This agreement is between {company} (\"Company\") and the client named below (\"Client\").",
      "s1": "1. Services",
      "s2": "2. Price and payment",
      "total": "Price",
      "s3": "3. Schedule",
      "sched": "Season: {start} to {end}. Service starts when snowfall reaches the agreed trigger depth.",
      "s4": "4. Trigger depth, storms and property",
      "chg": "Service is triggered at the depth listed above. Long storms may need more than one push. Client marks curbs, drains and landscape edges; Company is not responsible for damage to unmarked items under the snow.",
      "s5": "5. Insurance",
      "ins": "Company carries general liability insurance. Insurer: ____________________ Phone: ____________________",
      "s6": "6. Cancellations",
      "cxl": "Either party may end the seasonal agreement with 30 days written notice. Services already performed are billed.",
      "s7": "7. Electronic signatures",
      "esig": "The parties agree that this agreement may be signed electronically. An electronic signature has the same legal effect as a handwritten signature under the federal ESIGN Act (15 U.S.C. § 7001 et seq.) and the New Jersey Uniform Electronic Transactions Act (N.J.S.A. 12A:12-1 et seq.).",
      "draft": "Draft template. Have an attorney review the final wording before using it with clients."
    },
    es: {
      "title": "Acuerdo de Servicio de Remoción de Nieve",
      "intro": "Este acuerdo es entre {company} (\"la Compañía\") y el cliente nombrado abajo (\"el Cliente\").",
      "s1": "1. Servicios",
      "s2": "2. Precio y pago",
      "total": "Precio",
      "s3": "3. Calendario",
      "sched": "Temporada: {start} a {end}. El servicio empieza cuando la nieve llega a la profundidad acordada.",
      "s4": "4. Profundidad, tormentas y propiedad",
      "chg": "El servicio se activa a la profundidad indicada. Tormentas largas pueden necesitar más de una limpieza. El Cliente marca bordillos, drenajes y bordes de jardín; la Compañía no es responsable por daños a objetos no marcados bajo la nieve.",
      "s5": "5. Seguro",
      "ins": "La Compañía tiene seguro de responsabilidad civil. Aseguradora: ____________________ Teléfono: ____________________",
      "s6": "6. Cancelaciones",
      "cxl": "Cualquiera de las partes puede terminar el acuerdo de temporada con 30 días de aviso por escrito. Los servicios ya realizados se cobran.",
      "s7": "7. Firmas electrónicas",
      "esig": "Las partes acuerdan que este acuerdo puede firmarse electrónicamente. Una firma electrónica tiene el mismo efecto legal que una firma a mano bajo la ley federal ESIGN (15 U.S.C. § 7001 y siguientes) y la Ley Uniforme de Transacciones Electrónicas de Nueva Jersey (N.J.S.A. 12A:12-1 y siguientes).",
      "draft": "Plantilla en borrador. Un abogado debe revisar el texto final antes de usarlo con clientes."
    },
  },
  kickoffTasks: [
    { en: "Send the agreement for signature", es: "Enviar el acuerdo para firma", dueIn: 0, for: 'owner', pri: 'high' },
    { en: "Confirm the trigger depth, opening hours and storm contact", es: "Confirmar desde cuántas pulgadas se sale, el horario de apertura y el contacto para tormentas", dueIn: 2, for: 'owner' },
    { en: "Walk the site: mark curbs, drains, hydrants and where the piles go", es: "Recorrer el sitio: marcar bordillos, drenajes, hidrantes y dónde van los montones", dueIn: 3, for: 'owner' },
    { en: "Add the property to the storm route and assign the crew", es: "Agregar la propiedad a la ruta de tormenta y asignar la cuadrilla", dueIn: 4, for: 'owner' },
    { en: "Install the stakes before the first storm", es: "Poner las estacas antes de la primera tormenta", dueIn: 7, for: 'owner' },
  ],
  closeoutTasks: [
    { en: "Send the final invoice with the storm log", es: "Enviar la factura final con el registro de tormentas", dueIn: 0, for: 'owner', pri: 'high' },
    { en: "Pay the crew", es: "Pagar a la cuadrilla", dueIn: 2, for: 'owner' },
    { en: "Pull the stakes and check for curb or turf damage", es: "Quitar las estacas y revisar daños en bordillos o pasto", dueIn: 5, for: 'owner' },
    { en: "Offer the renewal for next season", es: "Ofrecer la renovación para la próxima temporada", dueIn: 10, for: 'owner', pri: 'low' },
  ],
  compliance: true,
});
