// VYNTEX EVENTS: industry pack for event setup & staffing.
// Everything industry-specific lives here. The app core never checks the industry id.
import type { IndustryPack } from '../types';

export const eventsPack: IndustryPack = {
  id: "events",
  product: "VYNTEX EVENTS",
  label: { en: "Event setup & staffing", es: "Montaje y personal para eventos" },
  blurb: { en: "For event staffing, setup and teardown teams.", es: "Para equipos de personal de servicio, montaje y desmontaje de eventos." },
  ticketPrefix: "VE-",
  recurring: false,
  sampleCompany: { name: "Sample Event Staffing LLC", initials: "ES", license: "Fully insured", phone: "609-555-0800", email: "events@example.com" },
  serviceTypes: [
    { id: "wedding", en: "Wedding", es: "Boda" },
    { id: "corporate", en: "Corporate event", es: "Evento corporativo" },
    { id: "party", en: "Private party", es: "Fiesta privada" },
    { id: "festival", en: "Festival / fair", es: "Festival / feria" },
    { id: "setup", en: "Setup & teardown", es: "Montaje y desmontaje" },
    { id: "service", en: "Servers & bartenders", es: "Meseros y bartenders" },
    { id: "security", en: "Security & parking", es: "Seguridad y estacionamiento" },
    { id: "other", en: "Other", es: "Otro" },
  ],
  terms: {
    en: {
      "workersPlural": "Staff members",
      "owner": "Owner",
      "projects": "Events",
      "project": "Event",
      "newProject": "New event",
      "back": "All events",
      "deleteProject": "Delete event",
      "name": "Event name",
      "noProjects": "No events match. Clear the filters or add a new event.",
      "subs": "Staff",
      "sub": "Staff member",
      "secAssign": "Who is working this event",
      "secSubPay": "Payments to staff",
      "addSubPay": "Pay staff",
      "paySub": "Pay staff",
      "paidSubs": "Paid to staff",
      "oweSubs": "You owe staff",
      "subLabor": "Staff labor",
      "newSub": "New staff member",
      "subName": "Full name or business name",
      "allSubs": "All staff",
      "addAssign": "Assign staff",
      "trade": "Role",
      "pt_project": "Per event (fixed price)",
      "contract": "Price",
      "contractBtn": "Agreement",
      "activeProjects": "Upcoming events",
      "contractValue": "Upcoming event value",
      "activeList": "Upcoming events",
      "secTasks": "Run of show & tasks",
      "newTask": "New checklist item",
      "task": "Checklist item",
      "secLog": "Notes from staff",
      "scope": "Work details (for the agreement)",
      "payTerms": "Price and billing (for the agreement)",
      "end": "Teardown date",
      "repeat": "Repeats",
      "rp_once": "One time",
      "rp_weekly": "Every week",
      "rp_biweekly": "Every 2 weeks",
      "rp_monthly": "Every month",
      "jobSite": "Venue",
      "contractTotal": "Job total",
      "st_progress": "Active",
      "industry": "Industry",
      "thanks": "Thank you for choosing {company}!",
      "address": "Venue",
      "materials": "Rentals & supplies",
      "secPurch": "Rentals & supplies",
      "addPurch": "Add rental or supply",
      "ev_start": "Event day",
      "ev_end": "Teardown",
      "start": "Event date"
    },
    es: {
      "workersPlural": "Miembros del personal",
      "owner": "Dueño",
      "projects": "Eventos",
      "project": "Evento",
      "newProject": "Nuevo evento",
      "back": "Todos los eventos",
      "deleteProject": "Borrar evento",
      "name": "Nombre del evento",
      "noProjects": "Ningún evento coincide. Quite los filtros o agregue uno.",
      "subs": "Personal",
      "sub": "Miembro del personal",
      "secAssign": "Quién trabaja en este evento",
      "secSubPay": "Pagos al personal",
      "addSubPay": "Pagar al personal",
      "paySub": "Pagar al personal",
      "paidSubs": "Pagado al personal",
      "oweSubs": "Usted debe al personal",
      "subLabor": "Mano de obra del personal",
      "newSub": "Nuevo miembro",
      "subName": "Nombre completo o de la empresa",
      "allSubs": "Todo el personal",
      "addAssign": "Asignar personal",
      "trade": "Función",
      "pt_project": "Por evento (precio fijo)",
      "contract": "Precio",
      "contractBtn": "Acuerdo",
      "activeProjects": "Próximos eventos",
      "contractValue": "Valor de próximos eventos",
      "activeList": "Próximos eventos",
      "secTasks": "Programa y tareas",
      "newTask": "Nuevo punto de la lista",
      "task": "Punto de la lista",
      "secLog": "Notas del personal",
      "scope": "Detalles del trabajo (para el acuerdo)",
      "payTerms": "Precio y cobro (para el acuerdo)",
      "end": "Fecha de desmontaje",
      "repeat": "Se repite",
      "rp_once": "Una vez",
      "rp_weekly": "Cada semana",
      "rp_biweekly": "Cada 2 semanas",
      "rp_monthly": "Cada mes",
      "jobSite": "Lugar",
      "contractTotal": "Total del trabajo",
      "st_progress": "Activo",
      "industry": "Industria",
      "thanks": "¡Gracias por elegir a {company}!",
      "address": "Lugar",
      "materials": "Rentas y suministros",
      "secPurch": "Rentas y suministros",
      "addPurch": "Agregar renta o suministro",
      "ev_start": "Día del evento",
      "ev_end": "Desmontaje",
      "start": "Fecha del evento"
    },
  },
  jobStatuses: ['estimate', 'contract', 'progress', 'hold', 'done'],
  kpis: ["activeJobs","activeValue","expectedProfit","clientsOwe","oweWorkers","newLeads"],
  agreement: {
    en: {
      "title": "Event Services Agreement",
      "intro": "This agreement is between {company} (\"Company\") and the client named below (\"Client\").",
      "s1": "1. Services and staff",
      "s2": "2. Price and payment",
      "total": "Price",
      "s3": "3. Schedule",
      "sched": "Event date: {start}. Teardown: {end}. Staff arrival and end times follow the run of show.",
      "s4": "4. Guest count, overtime and venue rules",
      "chg": "Final guest count is due 7 days before the event. Staff time beyond the agreed hours is billed as overtime. Client is responsible for venue permits and rules.",
      "s5": "5. Insurance",
      "ins": "Company carries general liability insurance. Insurer: ____________________ Phone: ____________________",
      "s6": "6. Cancellations",
      "cxl": "Cancellations more than 30 days before the event receive the deposit back minus rental costs already paid. Within 30 days, the deposit is non-refundable.",
      "s7": "7. Electronic signatures",
      "esig": "The parties agree that this agreement may be signed electronically. An electronic signature has the same legal effect as a handwritten signature under the federal ESIGN Act (15 U.S.C. § 7001 et seq.) and the New Jersey Uniform Electronic Transactions Act (N.J.S.A. 12A:12-1 et seq.).",
      "draft": "Draft template. Have an attorney review the final wording before using it with clients."
    },
    es: {
      "title": "Acuerdo de Servicios para Eventos",
      "intro": "Este acuerdo es entre {company} (\"la Compañía\") y el cliente nombrado abajo (\"el Cliente\").",
      "s1": "1. Servicios y personal",
      "s2": "2. Precio y pago",
      "total": "Precio",
      "s3": "3. Calendario",
      "sched": "Fecha del evento: {start}. Desmontaje: {end}. La llegada y salida del personal siguen el programa del evento.",
      "s4": "4. Invitados, horas extra y reglas del lugar",
      "chg": "El número final de invitados se entrega 7 días antes del evento. El tiempo del personal más allá de lo acordado se cobra como horas extra. El Cliente es responsable de permisos y reglas del lugar.",
      "s5": "5. Seguro",
      "ins": "La Compañía tiene seguro de responsabilidad civil. Aseguradora: ____________________ Teléfono: ____________________",
      "s6": "6. Cancelaciones",
      "cxl": "Cancelaciones con más de 30 días antes del evento reciben el depósito menos los costos de renta ya pagados. Dentro de 30 días, el depósito no es reembolsable.",
      "s7": "7. Firmas electrónicas",
      "esig": "Las partes acuerdan que este acuerdo puede firmarse electrónicamente. Una firma electrónica tiene el mismo efecto legal que una firma a mano bajo la ley federal ESIGN (15 U.S.C. § 7001 y siguientes) y la Ley Uniforme de Transacciones Electrónicas de Nueva Jersey (N.J.S.A. 12A:12-1 y siguientes).",
      "draft": "Plantilla en borrador. Un abogado debe revisar el texto final antes de usarlo con clientes."
    },
  },
  kickoffTasks: [
    { en: "Send the agreement and collect the deposit", es: "Enviar el acuerdo y cobrar el depósito", dueIn: 0, for: 'owner', pri: 'high' },
    { en: "Confirm the guest count, timeline and venue contact", es: "Confirmar el número de invitados, el programa y el contacto del lugar", dueIn: 3, for: 'owner' },
    { en: "Book the staff and send call times", es: "Apartar al personal y mandar las horas de llegada", dueIn: 5, for: 'owner' },
    { en: "Reserve rentals and supplies", es: "Apartar las rentas y los suministros", dueIn: 5, for: 'owner' },
    { en: "Walk the venue: load-in, kitchen, bar and parking", es: "Recorrer el lugar: entrada de carga, cocina, barra y estacionamiento", dueIn: 7, for: 'owner' },
  ],
  closeoutTasks: [
    { en: "Send the final invoice, with overtime if there was any", es: "Enviar la factura final, con tiempo extra si lo hubo", dueIn: 0, for: 'owner', pri: 'high' },
    { en: "Pay the staff", es: "Pagar al personal", dueIn: 1, for: 'owner' },
    { en: "Return the rentals and check for damage", es: "Devolver las rentas y revisar si hubo daños", dueIn: 1, for: 'owner' },
    { en: "Ask the client for a review", es: "Pedir una reseña al cliente", dueIn: 3, for: 'owner', pri: 'low' },
  ],
  compliance: true,
};
