// VYNTEX TURNOVER: industry pack for property turnover & make-ready.
// Everything industry-specific lives here. The app core never checks the industry id.
import type { IndustryPack } from '../types';
import { seed } from './seed';

export const turnoverPack: IndustryPack = {
  id: "turnover",
  product: "VYNTEX TURNOVER",
  label: { en: "Property turnover & make-ready", es: "Preparación de propiedades (make-ready)" },
  blurb: { en: "For make-ready crews that turn units between tenants.", es: "Para cuadrillas que preparan unidades entre inquilinos." },
  ticketPrefix: "VT-",
  recurring: false,
  sampleCompany: { name: "Sample Make-Ready Services LLC", initials: "MR", license: "NJ HIC #__________", phone: "609-555-0700", email: "work@example.com" },
  serviceTypes: [
    { id: "full", en: "Full turnover", es: "Preparación completa" },
    { id: "paint", en: "Paint", es: "Pintura" },
    { id: "clean", en: "Cleaning", es: "Limpieza" },
    { id: "flooring", en: "Flooring & carpet", es: "Pisos y alfombra" },
    { id: "repairs", en: "Repairs", es: "Reparaciones" },
    { id: "appliance", en: "Appliances", es: "Electrodomésticos" },
    { id: "other", en: "Other", es: "Otro" },
  ],
  terms: {
    en: {
      "owner": "Owner",
      "projects": "Units",
      "project": "Unit",
      "newProject": "New unit turnover",
      "back": "All units",
      "deleteProject": "Delete unit",
      "name": "Unit (e.g. Unit 2B)",
      "noProjects": "No jobs match. Clear the filters or add a new job.",
      "subs": "Subcontractors",
      "sub": "Subcontractor",
      "secAssign": "Who is doing what",
      "secSubPay": "Payments to subcontractors",
      "addSubPay": "Pay a subcontractor",
      "paySub": "Pay a subcontractor",
      "paidSubs": "Paid to subs",
      "oweSubs": "You owe subs",
      "subLabor": "Subcontractor labor",
      "newSub": "New subcontractor",
      "subName": "Full name or business name",
      "allSubs": "All subcontractors",
      "addAssign": "Assign a subcontractor",
      "trade": "Trade",
      "pt_project": "Per unit (fixed price)",
      "contract": "Price",
      "contractBtn": "Work order",
      "activeProjects": "Active units",
      "contractValue": "Active unit value",
      "activeList": "Active units",
      "secTasks": "Checklist & tasks",
      "newTask": "New checklist item",
      "task": "Checklist item",
      "secLog": "Notes from the crew",
      "scope": "Work details (for the agreement)",
      "payTerms": "Price and billing (for the agreement)",
      "end": "Ready date",
      "repeat": "Repeats",
      "rp_once": "One time",
      "rp_weekly": "Every week",
      "rp_biweekly": "Every 2 weeks",
      "rp_monthly": "Every month",
      "jobSite": "Service address",
      "contractTotal": "Job total",
      "st_progress": "Active",
      "industry": "Industry",
      "thanks": "Thank you for choosing {company}!",
      "client": "Property manager / owner",
      "address": "Property address",
      "materials": "Materials",
      "secPurch": "Materials",
      "ev_start": "Turnover starts",
      "ev_end": "Ready for move-in",
      "start": "Start date"
    },
    es: {
      "owner": "Dueño",
      "projects": "Unidades",
      "project": "Unidad",
      "newProject": "Nueva unidad",
      "back": "Todas las unidades",
      "deleteProject": "Borrar unidad",
      "name": "Unidad (ej. Unidad 2B)",
      "noProjects": "Ningún trabajo coincide. Quite los filtros o agregue uno.",
      "subs": "Subcontratistas",
      "sub": "Subcontratista",
      "secAssign": "Quién hace qué",
      "secSubPay": "Pagos a subcontratistas",
      "addSubPay": "Pagar a subcontratista",
      "paySub": "Pagar a subcontratista",
      "paidSubs": "Pagado a subs",
      "oweSubs": "Usted debe a subs",
      "subLabor": "Mano de obra de subs",
      "newSub": "Nuevo subcontratista",
      "subName": "Nombre completo o de la empresa",
      "allSubs": "Todos los subcontratistas",
      "addAssign": "Asignar subcontratista",
      "trade": "Oficio",
      "pt_project": "Por unidad (precio fijo)",
      "contract": "Precio",
      "contractBtn": "Orden de trabajo",
      "activeProjects": "Unidades activas",
      "contractValue": "Valor de unidades activas",
      "activeList": "Unidades activas",
      "secTasks": "Lista de tareas",
      "newTask": "Nuevo punto de la lista",
      "task": "Punto de la lista",
      "secLog": "Notas de la cuadrilla",
      "scope": "Detalles del trabajo (para el acuerdo)",
      "payTerms": "Precio y cobro (para el acuerdo)",
      "end": "Fecha lista",
      "repeat": "Se repite",
      "rp_once": "Una vez",
      "rp_weekly": "Cada semana",
      "rp_biweekly": "Cada 2 semanas",
      "rp_monthly": "Cada mes",
      "jobSite": "Dirección del servicio",
      "contractTotal": "Total del trabajo",
      "st_progress": "Activo",
      "industry": "Industria",
      "thanks": "¡Gracias por elegir a {company}!",
      "client": "Administrador / dueño",
      "address": "Dirección de la propiedad",
      "materials": "Materiales",
      "secPurch": "Materiales",
      "ev_start": "Inicia la preparación",
      "ev_end": "Lista para mudanza",
      "start": "Fecha de inicio"
    },
  },
  grammar: { es: { job: 'f' } },
  jobStatuses: ['estimate', 'contract', 'progress', 'hold', 'done'],
  kpis: ["activeJobs","activeValue","expectedProfit","clientsOwe","oweWorkers","newLeads"],
  agreement: {
    en: {
      "title": "Unit Turnover Work Order",
      "intro": "This agreement is between {company} (\"Company\") and the client named below (\"Client\").",
      "s1": "1. Scope of work",
      "s2": "2. Price and payment",
      "total": "Price",
      "s3": "3. Schedule",
      "sched": "Start: {start}. Ready for move-in: {end}.",
      "s4": "4. Changes and approvals",
      "chg": "Any extra repair found during the turnover is photographed and approved by the property manager before the work is done. Company provides before and after photos of every room.",
      "s5": "5. Insurance",
      "ins": "Company carries general liability insurance. Insurer: ____________________ Phone: ____________________",
      "s6": "6. Cancellations",
      "cxl": "The work order may be cancelled before work begins. Work already completed and materials purchased are billed.",
      "s7": "7. Electronic signatures",
      "esig": "The parties agree that this agreement may be signed electronically. An electronic signature has the same legal effect as a handwritten signature under the federal ESIGN Act (15 U.S.C. § 7001 et seq.) and the New Jersey Uniform Electronic Transactions Act (N.J.S.A. 12A:12-1 et seq.).",
      "draft": "Draft template. Have an attorney review the final wording before using it with clients."
    },
    es: {
      "title": "Orden de Trabajo de Preparación de Unidad",
      "intro": "Este acuerdo es entre {company} (\"la Compañía\") y el cliente nombrado abajo (\"el Cliente\").",
      "s1": "1. Alcance del trabajo",
      "s2": "2. Precio y pago",
      "total": "Precio",
      "s3": "3. Calendario",
      "sched": "Inicio: {start}. Lista para mudanza: {end}.",
      "s4": "4. Cambios y aprobaciones",
      "chg": "Cualquier reparación extra encontrada se fotografía y la aprueba el administrador antes de hacerse. La Compañía entrega fotos de antes y después de cada cuarto.",
      "s5": "5. Seguro",
      "ins": "La Compañía tiene seguro de responsabilidad civil. Aseguradora: ____________________ Teléfono: ____________________",
      "s6": "6. Cancelaciones",
      "cxl": "La orden puede cancelarse antes de empezar. El trabajo ya realizado y los materiales comprados se cobran.",
      "s7": "7. Firmas electrónicas",
      "esig": "Las partes acuerdan que este acuerdo puede firmarse electrónicamente. Una firma electrónica tiene el mismo efecto legal que una firma a mano bajo la ley federal ESIGN (15 U.S.C. § 7001 y siguientes) y la Ley Uniforme de Transacciones Electrónicas de Nueva Jersey (N.J.S.A. 12A:12-1 y siguientes).",
      "draft": "Plantilla en borrador. Un abogado debe revisar el texto final antes de usarlo con clientes."
    },
  },
  kickoffTasks: [
    { en: "Send the work order for approval", es: "Enviar la orden de trabajo para aprobación", dueIn: 0, for: 'owner', pri: 'high' },
    { en: "Get the keys or lockbox code and confirm the ready date", es: "Conseguir las llaves o el código de la caja de llaves y confirmar la fecha lista", dueIn: 1, for: 'owner' },
    { en: "Walk the unit and take before photos", es: "Recorrer la unidad y tomar fotos de antes", dueIn: 1, for: 'owner' },
    { en: "Order the materials", es: "Pedir los materiales", dueIn: 2, for: 'owner' },
    { en: "Schedule the subcontractors in order: repairs, paint, flooring, cleaning", es: "Programar a los subcontratistas en orden: reparaciones, pintura, pisos y limpieza", dueIn: 2, for: 'owner' },
  ],
  closeoutTasks: [
    { en: "Final walkthrough with photos for the manager", es: "Recorrido final con fotos para el administrador", dueIn: 0, for: 'owner', pri: 'high' },
    { en: "Send the invoice", es: "Enviar la factura", dueIn: 0, for: 'owner', pri: 'high' },
    { en: "Return the keys and remove the lockbox", es: "Devolver las llaves y quitar la caja de llaves", dueIn: 1, for: 'owner' },
    { en: "Pay the subcontractors", es: "Pagar a los subcontratistas", dueIn: 3, for: 'owner' },
  ],
  compliance: true,
  seed,
};
