// VYNTEX LANDSCAPE: industry pack for landscaping.
// Everything industry-specific lives here. The app core never checks the industry id.
import type { IndustryPack } from '../types';
import { fieldPack } from '../blueprint';

export const landscapePack: IndustryPack = /* @__PURE__ */ fieldPack({
  id: "landscape",
  product: "VYNTEX LANDSCAPE",
  label: { en: "Landscaping", es: "Jardinería" },
  blurb: { en: "For lawn care, landscape installs and hardscape crews.", es: "Para mantenimiento de césped, instalación de jardines y cuadrillas de adoquín." },
  ticketPrefix: "VL-",
  recurring: true,
  sampleCompany: { name: "Greenline Sample Landscaping LLC", initials: "GL", license: "Fully insured", phone: "609-555-0300", email: "samplelandscaping@example.com" },
  serviceTypes: [
    { id: "lawn", en: "Lawn maintenance", es: "Mantenimiento de césped" },
    { id: "design", en: "Landscape design & install", es: "Diseño e instalación" },
    { id: "hardscape", en: "Pavers & hardscape", es: "Adoquines y hardscape" },
    { id: "mulch", en: "Mulch & planting", es: "Mulch y plantas" },
    { id: "trees", en: "Tree & shrub trimming", es: "Poda de árboles y arbustos" },
    { id: "cleanup", en: "Spring / fall cleanup", es: "Limpieza de primavera / otoño" },
    { id: "irrigation", en: "Irrigation", es: "Riego" },
    { id: "snow", en: "Snow removal", es: "Remoción de nieve" },
    { id: "other", en: "Other", es: "Otro" },
  ],
  terms: {
    en: {
      "workersPlural": "Crew members",
      "owner": "Owner",
      "projects": "Jobs",
      "project": "Job",
      "newProject": "New job",
      "back": "All jobs",
      "deleteProject": "Delete job",
      "name": "Job name",
      "noProjects": "No jobs match. Clear the filters or add a new job.",
      "subs": "Crew",
      "sub": "Crew member",
      "secAssign": "Who is on the crew",
      "secSubPay": "Payments to crew",
      "addSubPay": "Pay a crew member",
      "paySub": "Pay a crew member",
      "paidSubs": "Paid to crew",
      "oweSubs": "You owe crew",
      "subLabor": "Crew labor",
      "newSub": "New crew member",
      "subName": "Full name or business name",
      "allSubs": "All crew",
      "addAssign": "Assign crew",
      "trade": "Role",
      "materials": "Materials & plants",
      "secPurch": "Materials & plants",
      "addPurch": "Add materials",
      "scope": "Work details (for the agreement)",
      "payTerms": "Price and billing (for the agreement)",
      "contract": "Price",
      "contractBtn": "Agreement",
      "activeProjects": "Active jobs",
      "contractValue": "Active job value",
      "activeList": "Active jobs",
      "secTasks": "Checklist & tasks",
      "newTask": "New checklist item",
      "task": "Checklist item",
      "secLog": "Notes from the crew",
      "ev_start": "Service visit",
      "ev_end": "Job ends",
      "start": "Start date / first visit",
      "end": "End date (optional)",
      "repeat": "Repeats",
      "rp_once": "One time",
      "rp_weekly": "Every week",
      "rp_biweekly": "Every 2 weeks",
      "rp_monthly": "Every month",
      "jobSite": "Service address",
      "contractTotal": "Job total",
      "st_progress": "Active",
      "thanks": "Thank you for choosing Greenline Sample Landscaping!",
      "industry": "Industry",
      "pt_project": "Per job (fixed price)",
      "forProject": "Job",
      "convert": "Make it a job",
      "converted": "Job created",
      "search": "Search client, address or job",
      "confirmReset": "Throw away your edits and rebuild this document from the job details?"
    },
    es: {
      "workersPlural": "Miembros de cuadrilla",
      "owner": "Dueño",
      "projects": "Trabajos",
      "project": "Trabajo",
      "newProject": "Nuevo trabajo",
      "back": "Todos los trabajos",
      "deleteProject": "Borrar trabajo",
      "name": "Nombre del trabajo",
      "noProjects": "Ningún trabajo coincide. Quite los filtros o agregue uno.",
      "subs": "Cuadrilla",
      "sub": "Miembro de cuadrilla",
      "secAssign": "Quién está en la cuadrilla",
      "secSubPay": "Pagos a la cuadrilla",
      "addSubPay": "Pagar a un miembro",
      "paySub": "Pagar a un miembro",
      "paidSubs": "Pagado a la cuadrilla",
      "oweSubs": "Usted debe a la cuadrilla",
      "subLabor": "Mano de obra",
      "newSub": "Nuevo miembro",
      "subName": "Nombre completo o de la empresa",
      "allSubs": "Toda la cuadrilla",
      "addAssign": "Asignar cuadrilla",
      "trade": "Función",
      "materials": "Materiales y plantas",
      "secPurch": "Materiales y plantas",
      "addPurch": "Agregar materiales",
      "scope": "Detalles del trabajo (para el acuerdo)",
      "payTerms": "Precio y cobro (para el acuerdo)",
      "contract": "Precio",
      "contractBtn": "Acuerdo",
      "activeProjects": "Trabajos activos",
      "contractValue": "Valor de trabajos activos",
      "activeList": "Trabajos activos",
      "secTasks": "Lista de tareas",
      "newTask": "Nuevo punto de la lista",
      "task": "Punto de la lista",
      "secLog": "Notas de la cuadrilla",
      "ev_start": "Visita de servicio",
      "ev_end": "Termina el trabajo",
      "start": "Fecha de inicio / primera visita",
      "end": "Fecha final (opcional)",
      "repeat": "Se repite",
      "rp_once": "Una vez",
      "rp_weekly": "Cada semana",
      "rp_biweekly": "Cada 2 semanas",
      "rp_monthly": "Cada mes",
      "jobSite": "Dirección del servicio",
      "contractTotal": "Total del trabajo",
      "st_progress": "Activo",
      "thanks": "¡Gracias por elegir a Greenline Sample Landscaping!",
      "industry": "Industria",
      "pt_project": "Por trabajo (precio fijo)",
      "forProject": "Trabajo",
      "convert": "Convertir en trabajo",
      "converted": "Trabajo creado",
      "search": "Buscar cliente, dirección o trabajo",
      "confirmReset": "¿Descartar sus cambios y volver a crear este documento con los datos del trabajo?"
    },
  },
  jobStatuses: ['estimate', 'contract', 'progress', 'hold', 'done'],
  kpis: ["activeJobs","recurringClients","visitsThisWeek","clientsOwe","oweWorkers","newLeads"],
  agreement: {
    en: {
      "title": "Landscaping Service Agreement",
      "intro": "This agreement is between {company} (\"Company\") and the client named below (\"Client\").",
      "s1": "1. Services",
      "s2": "2. Price and payment",
      "total": "Price",
      "s3": "3. Schedule",
      "sched": "Start date: {start}. Recurring maintenance follows the agreed schedule for the season. Installation work is estimated to finish by {end}.",
      "s4": "4. Weather, changes and materials",
      "chg": "Visits may shift because of rain, snow or unsafe conditions. Changes to the work or materials must be agreed in writing before they are done. Plants carry the nursery warranty only when watered as instructed.",
      "s5": "5. Insurance",
      "ins": "Company carries general liability insurance. Insurer: ____________________ Phone: ____________________",
      "s6": "6. Cancellations and access",
      "cxl": "Maintenance can be paused or cancelled with 7 days written notice. For home improvement installation work, you may cancel before midnight of the third business day after receiving a signed copy of this agreement. Please keep gates unlocked and pets inside on service days.",
      "s7": "7. Electronic signatures",
      "esig": "The parties agree that this agreement may be signed electronically. An electronic signature has the same legal effect as a handwritten signature under the federal ESIGN Act (15 U.S.C. § 7001 et seq.) and the New Jersey Uniform Electronic Transactions Act (N.J.S.A. 12A:12-1 et seq.).",
      "draft": "Draft template. Have an attorney review the final wording before using it with clients."
    },
    es: {
      "title": "Acuerdo de Servicio de Jardinería",
      "intro": "Este acuerdo es entre {company} (\"la Compañía\") y el cliente nombrado abajo (\"el Cliente\").",
      "s1": "1. Servicios",
      "s2": "2. Precio y pago",
      "total": "Precio",
      "s3": "3. Calendario",
      "sched": "Fecha de inicio: {start}. El mantenimiento recurrente sigue el calendario acordado para la temporada. Los trabajos de instalación terminan aproximadamente el {end}.",
      "s4": "4. Clima, cambios y materiales",
      "chg": "Las visitas pueden moverse por lluvia, nieve o condiciones inseguras. Los cambios al trabajo o a los materiales deben acordarse por escrito antes de hacerse. Las plantas tienen la garantía del vivero solo si se riegan según las instrucciones.",
      "s5": "5. Seguro",
      "ins": "La Compañía tiene seguro de responsabilidad civil. Aseguradora: ____________________ Teléfono: ____________________",
      "s6": "6. Cancelaciones y acceso",
      "cxl": "El mantenimiento puede pausarse o cancelarse con 7 días de aviso por escrito. Para trabajos de instalación de mejoras al hogar, usted puede cancelar antes de la medianoche del tercer día hábil después de recibir una copia firmada de este acuerdo. Mantenga los portones abiertos y las mascotas adentro los días de servicio.",
      "s7": "7. Firmas electrónicas",
      "esig": "Las partes acuerdan que este acuerdo puede firmarse electrónicamente. Una firma electrónica tiene el mismo efecto legal que una firma a mano bajo la ley federal ESIGN (15 U.S.C. § 7001 y siguientes) y la Ley Uniforme de Transacciones Electrónicas de Nueva Jersey (N.J.S.A. 12A:12-1 y siguientes).",
      "draft": "Plantilla en borrador. Un abogado debe revisar el texto final antes de usarlo con clientes."
    },
  },
  kickoffTasks: [
    { en: "Send the agreement and collect the deposit", es: "Enviar el acuerdo y cobrar el depósito", dueIn: 0, for: 'owner', pri: 'high' },
    { en: "Request the utility mark-out (811) if the job involves digging", es: "Pedir la marcación de servicios (811) si el trabajo lleva excavación", dueIn: 1, for: 'owner', pri: 'high' },
    { en: "Walk the property: gate code, sprinkler heads, pets", es: "Recorrer la propiedad: código del portón, aspersores, mascotas", dueIn: 2, for: 'owner' },
    { en: "Order plants and materials", es: "Pedir plantas y materiales", dueIn: 3, for: 'owner' },
    { en: "Put the job on the crew route and tell the client the day", es: "Poner el trabajo en la ruta de la cuadrilla y avisar el día al cliente", dueIn: 4, for: 'owner' },
  ],
  closeoutTasks: [
    { en: "Walk the finished work with the client", es: "Recorrer el trabajo terminado con el cliente", dueIn: 0, for: 'owner', pri: 'high' },
    { en: "Send the final invoice", es: "Enviar la factura final", dueIn: 1, for: 'owner', pri: 'high' },
    { en: "Send watering and care instructions", es: "Enviar instrucciones de riego y cuidado", dueIn: 1, for: 'owner' },
    { en: "Ask for a review and offer a maintenance plan", es: "Pedir una reseña y ofrecer un plan de mantenimiento", dueIn: 5, for: 'owner', pri: 'low' },
  ],
  compliance: true,
});
